### ISSUE TITLE
DSM pre-requisite details in document

### ISSUE THREAD

**Issue by tsheth** [trend206/dsp3#1]
Its a great work for developing DSP3 Jeff.  I am getting few errors in DSM 10.1 {\"error\":{\"message\":\"RESTEASY003210: Could not find resource for full path: https://<IP>/rest/relays?background=False&failed=False\"}}"

 is it possible to get the DSM version pre-requisites in document?

**Comment by jeffthorne** [comment]
Thanks for the feedback Tejas. Most of the calls were tested against DSaS. What calls are you seeing the errors on and I will take a look.

**Comment by tsheth** [comment]
I am getting similar error for some of the resource fetching functions.
https://github.com/trend206/dsp3/blob/master/examples/relays.py
https://github.com/trend206/dsp3/blob/master/examples/host.py


Authentication and get_version functions are working fine.

**Comment by jeffthorne** [comment]
You need to go into Administration -> system settings -> advanced and enable the SOAP API service. This enables the SOAP and REST APIs. Right now they are turned off so none of your calls will work other than auth and check version.
